require('plugins')
require('cmp_settings')
require("cmp").setup({})
require("mason").setup()
require("other")
require("discord")
require("lsp")
require("theme")
vim.cmd('set nu')
vim.cmd('set tabstop=4')
vim.cmd('set softtabstop=4')
vim.cmd('set shiftwidth=4')
vim.cmd('set ruler')
vim.cmd('set noswapfile')
vim.cmd('filetype on')
vim.cmd('filetype plugin on')
vim.cmd('syntax on')
